export const PERMISSIONS = [
  "project.read",
  "project.create",
  "project.update",
  "project.delete",
  "task.read",
  "task.create",
  "task.assign",
  "task.update",
  "lead.read",
  "lead.create",
  "lead.assign",
  "lead.update",
  "client.read",
  "client.manage",
  "deal.read",
  "deal.manage",
  "team.read",
  "team.manage",
  "user.read",
  "user.manage",
  "daily_update.read",
  "daily_update.review",
  "leave.read",
  "leave.approve",
  "meeting.manage",
  "chat.access",
  "file.manage",
  "marketing.read",
  "marketing.manage",
  "quotation.create",
  "invoice.create",
  "invoice.read",
  "payment.manage",
  "expense.manage",
  "report.read",
  "automation.manage",
  "admin.access",
  "audit.read",
  "settings.manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  "Organization Owner": [...PERMISSIONS],
  Admin: PERMISSIONS.filter((p) => p !== "settings.manage") as Permission[],
  "Project Manager": [
    "project.read",
    "project.create",
    "project.update",
    "task.read",
    "task.create",
    "task.assign",
    "task.update",
    "client.read",
    "team.read",
    "user.read",
    "daily_update.read",
    "daily_update.review",
    "leave.read",
    "leave.approve",
    "meeting.manage",
    "chat.access",
    "file.manage",
    "report.read",
    "expense.manage",
  ],
  "Team Lead": [
    "project.read",
    "task.read",
    "task.create",
    "task.assign",
    "task.update",
    "team.read",
    "user.read",
    "daily_update.read",
    "daily_update.review",
    "leave.read",
    "leave.approve",
    "meeting.manage",
    "chat.access",
    "file.manage",
    "report.read",
  ],
  "Sales Manager": [
    "lead.read",
    "lead.create",
    "lead.assign",
    "lead.update",
    "client.read",
    "client.manage",
    "deal.read",
    "deal.manage",
    "project.read",
    "quotation.create",
    "invoice.create",
    "invoice.read",
    "meeting.manage",
    "chat.access",
    "report.read",
    "marketing.read",
  ],
  "Sales Executive": [
    "lead.read",
    "lead.create",
    "lead.update",
    "client.read",
    "deal.read",
    "deal.manage",
    "meeting.manage",
    "chat.access",
  ],
  "Team Member": [
    "project.read",
    "task.read",
    "task.update",
    "team.read",
    "user.read",
    "daily_update.read",
    "leave.read",
    "chat.access",
    "file.manage",
    "meeting.manage",
  ],
  "Finance User": [
    "invoice.read",
    "invoice.create",
    "quotation.create",
    "payment.manage",
    "expense.manage",
    "client.read",
    "project.read",
    "report.read",
  ],
  Client: ["project.read", "task.read", "invoice.read", "file.manage"],
};

export const ROLE_NAMES = Object.keys(ROLE_PERMISSIONS);

/** Maps a live workspace membership role onto the product's role definition. */
export const ORG_ROLE_TO_ROLE_NAME: Record<string, string> = {
  owner: "Organization Owner",
  admin: "Admin",
  manager: "Project Manager",
  member: "Team Member",
};

export const ORG_ROLE_DESCRIPTIONS: Record<string, string> = {
  owner: "Full control of the workspace, including settings and billing.",
  admin: "Manages people, teams, projects and delivery across the workspace.",
  manager: "Runs projects and tasks, reviews updates and approves leave.",
  member: "Works on assigned projects and tasks, and collaborates with the team.",
};
