/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DailyUpdatesRouteImport } from './routes/daily-updates'
import { Route as FilesRouteImport } from './routes/files'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProjectTemplatesRouteImport } from './routes/project-templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AdminApiRouteImport } from './routes/admin.api'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AutomationIndexRouteImport } from './routes/automation.index'
import { Route as AutomationAiUsageRouteImport } from './routes/automation.ai-usage'
import { Route as AutomationLogsRouteImport } from './routes/automation.logs'
import { Route as AutomationTemplatesRouteImport } from './routes/automation.templates'
import { Route as BusinessQuotationsRouteImport } from './routes/business.quotations'
import { Route as CrmCompaniesRouteImport } from './routes/crm.companies'
import { Route as CrmContactsRouteImport } from './routes/crm.contacts'
import { Route as MarketingIndexRouteImport } from './routes/marketing.index'
import { Route as MarketingCampaignsRouteImport } from './routes/marketing.campaigns'
import { Route as MarketingContentCalendarRouteImport } from './routes/marketing.content-calendar'
import { Route as MarketingContentLibraryRouteImport } from './routes/marketing.content-library'
import { Route as MarketingInboxRouteImport } from './routes/marketing.inbox'
import { Route as MarketingMetaRouteImport } from './routes/marketing.meta'
import { Route as MarketingMetaLeadsRouteImport } from './routes/marketing.meta-leads'
import { Route as MarketingReportsRouteImport } from './routes/marketing.reports'
import { Route as MarketingScheduledRouteImport } from './routes/marketing.scheduled'
import { Route as MarketingWhatsappRouteImport } from './routes/marketing.whatsapp'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsMyRouteImport } from './routes/projects.my'
import { Route as ReportsProjectsRouteImport } from './routes/reports.projects'
import { Route as ReportsTeamsRouteImport } from './routes/reports.teams'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin.employees'
import { Route as AuthenticatedAdminProfileRouteImport } from './routes/_authenticated/admin.profile'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminWorkspaceRouteImport } from './routes/_authenticated/admin.workspace'
import { Route as AuthenticatedBusinessExpensesRouteImport } from './routes/_authenticated/business.expenses'
import { Route as AuthenticatedBusinessInvoicesRouteImport } from './routes/_authenticated/business.invoices'
import { Route as AuthenticatedBusinessPaymentsRouteImport } from './routes/_authenticated/business.payments'
import { Route as AuthenticatedCrmClientsRouteImport } from './routes/_authenticated/crm.clients'
import { Route as AuthenticatedCrmDealsRouteImport } from './routes/_authenticated/crm.deals'
import { Route as AuthenticatedCrmLeadsRouteImport } from './routes/_authenticated/crm.leads'
import { Route as AuthenticatedCrmPipelineRouteImport } from './routes/_authenticated/crm.pipeline'
import { Route as AuthenticatedReportsCrmRouteImport } from './routes/_authenticated/reports.crm'
import { Route as AuthenticatedSettingsWorkspaceRouteImport } from './routes/_authenticated/settings.workspace'
import { Route as AuthenticatedWorkDocumentsRouteImport } from './routes/_authenticated/work.documents'
import { Route as AuthenticatedWorkProjectsRouteImport } from './routes/_authenticated/work.projects'
import { Route as AuthenticatedWorkTasksRouteImport } from './routes/_authenticated/work.tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyUpdatesRoute = DailyUpdatesRouteImport.update({
  id: '/daily-updates',
  path: '/daily-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectTemplatesRoute = ProjectTemplatesRouteImport.update({
  id: '/project-templates',
  path: '/project-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/admin/api',
  path: '/admin/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationIndexRoute = AutomationIndexRouteImport.update({
  id: '/automation/',
  path: '/automation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationAiUsageRoute = AutomationAiUsageRouteImport.update({
  id: '/automation/ai-usage',
  path: '/automation/ai-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationLogsRoute = AutomationLogsRouteImport.update({
  id: '/automation/logs',
  path: '/automation/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationTemplatesRoute = AutomationTemplatesRouteImport.update({
  id: '/automation/templates',
  path: '/automation/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessQuotationsRoute = BusinessQuotationsRouteImport.update({
  id: '/business/quotations',
  path: '/business/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCompaniesRoute = CrmCompaniesRouteImport.update({
  id: '/crm/companies',
  path: '/crm/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/crm/contacts',
  path: '/crm/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCampaignsRoute = MarketingCampaignsRouteImport.update({
  id: '/marketing/campaigns',
  path: '/marketing/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingContentCalendarRoute =
  MarketingContentCalendarRouteImport.update({
    id: '/marketing/content-calendar',
    path: '/marketing/content-calendar',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketingContentLibraryRoute = MarketingContentLibraryRouteImport.update({
  id: '/marketing/content-library',
  path: '/marketing/content-library',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingInboxRoute = MarketingInboxRouteImport.update({
  id: '/marketing/inbox',
  path: '/marketing/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingMetaRoute = MarketingMetaRouteImport.update({
  id: '/marketing/meta',
  path: '/marketing/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingMetaLeadsRoute = MarketingMetaLeadsRouteImport.update({
  id: '/marketing/meta-leads',
  path: '/marketing/meta-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingReportsRoute = MarketingReportsRouteImport.update({
  id: '/marketing/reports',
  path: '/marketing/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingScheduledRoute = MarketingScheduledRouteImport.update({
  id: '/marketing/scheduled',
  path: '/marketing/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingWhatsappRoute = MarketingWhatsappRouteImport.update({
  id: '/marketing/whatsapp',
  path: '/marketing/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsMyRoute = ProjectsMyRouteImport.update({
  id: '/projects/my',
  path: '/projects/my',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsProjectsRoute = ReportsProjectsRouteImport.update({
  id: '/reports/projects',
  path: '/reports/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsTeamsRoute = ReportsTeamsRouteImport.update({
  id: '/reports/teams',
  path: '/reports/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/admin/employees',
    path: '/admin/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProfileRoute =
  AuthenticatedAdminProfileRouteImport.update({
    id: '/admin/profile',
    path: '/admin/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminWorkspaceRoute =
  AuthenticatedAdminWorkspaceRouteImport.update({
    id: '/admin/workspace',
    path: '/admin/workspace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessExpensesRoute =
  AuthenticatedBusinessExpensesRouteImport.update({
    id: '/business/expenses',
    path: '/business/expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessInvoicesRoute =
  AuthenticatedBusinessInvoicesRouteImport.update({
    id: '/business/invoices',
    path: '/business/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessPaymentsRoute =
  AuthenticatedBusinessPaymentsRouteImport.update({
    id: '/business/payments',
    path: '/business/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmClientsRoute = AuthenticatedCrmClientsRouteImport.update({
  id: '/crm/clients',
  path: '/crm/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmDealsRoute = AuthenticatedCrmDealsRouteImport.update({
  id: '/crm/deals',
  path: '/crm/deals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmLeadsRoute = AuthenticatedCrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmPipelineRoute =
  AuthenticatedCrmPipelineRouteImport.update({
    id: '/crm/pipeline',
    path: '/crm/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsCrmRoute = AuthenticatedReportsCrmRouteImport.update({
  id: '/reports/crm',
  path: '/reports/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsWorkspaceRoute =
  AuthenticatedSettingsWorkspaceRouteImport.update({
    id: '/settings/workspace',
    path: '/settings/workspace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkDocumentsRoute =
  AuthenticatedWorkDocumentsRouteImport.update({
    id: '/work/documents',
    path: '/work/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkProjectsRoute =
  AuthenticatedWorkProjectsRouteImport.update({
    id: '/work/projects',
    path: '/work/projects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkTasksRoute = AuthenticatedWorkTasksRouteImport.update({
  id: '/work/tasks',
  path: '/work/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/daily-updates': typeof DailyUpdatesRoute
  '/files': typeof FilesRoute
  '/kanban': typeof KanbanRoute
  '/leave': typeof LeaveRoute
  '/meetings': typeof MeetingsRoute
  '/milestones': typeof MilestonesRoute
  '/notifications': typeof NotificationsRoute
  '/project-templates': typeof ProjectTemplatesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/timeline': typeof TimelineRoute
  '/users': typeof UsersRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/automation/ai-usage': typeof AutomationAiUsageRoute
  '/automation/logs': typeof AutomationLogsRoute
  '/automation/templates': typeof AutomationTemplatesRoute
  '/business/quotations': typeof BusinessQuotationsRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/content-calendar': typeof MarketingContentCalendarRoute
  '/marketing/content-library': typeof MarketingContentLibraryRoute
  '/marketing/inbox': typeof MarketingInboxRoute
  '/marketing/meta': typeof MarketingMetaRoute
  '/marketing/meta-leads': typeof MarketingMetaLeadsRoute
  '/marketing/reports': typeof MarketingReportsRoute
  '/marketing/scheduled': typeof MarketingScheduledRoute
  '/marketing/whatsapp': typeof MarketingWhatsappRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/my': typeof ProjectsMyRoute
  '/reports/projects': typeof ReportsProjectsRoute
  '/reports/teams': typeof ReportsTeamsRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/automation/': typeof AutomationIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workspace': typeof AuthenticatedAdminWorkspaceRoute
  '/business/expenses': typeof AuthenticatedBusinessExpensesRoute
  '/business/invoices': typeof AuthenticatedBusinessInvoicesRoute
  '/business/payments': typeof AuthenticatedBusinessPaymentsRoute
  '/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/crm/deals': typeof AuthenticatedCrmDealsRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/crm/pipeline': typeof AuthenticatedCrmPipelineRoute
  '/reports/crm': typeof AuthenticatedReportsCrmRoute
  '/settings/workspace': typeof AuthenticatedSettingsWorkspaceRoute
  '/work/documents': typeof AuthenticatedWorkDocumentsRoute
  '/work/projects': typeof AuthenticatedWorkProjectsRoute
  '/work/tasks': typeof AuthenticatedWorkTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/daily-updates': typeof DailyUpdatesRoute
  '/files': typeof FilesRoute
  '/kanban': typeof KanbanRoute
  '/leave': typeof LeaveRoute
  '/meetings': typeof MeetingsRoute
  '/milestones': typeof MilestonesRoute
  '/notifications': typeof NotificationsRoute
  '/project-templates': typeof ProjectTemplatesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/timeline': typeof TimelineRoute
  '/users': typeof UsersRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/automation/ai-usage': typeof AutomationAiUsageRoute
  '/automation/logs': typeof AutomationLogsRoute
  '/automation/templates': typeof AutomationTemplatesRoute
  '/business/quotations': typeof BusinessQuotationsRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/content-calendar': typeof MarketingContentCalendarRoute
  '/marketing/content-library': typeof MarketingContentLibraryRoute
  '/marketing/inbox': typeof MarketingInboxRoute
  '/marketing/meta': typeof MarketingMetaRoute
  '/marketing/meta-leads': typeof MarketingMetaLeadsRoute
  '/marketing/reports': typeof MarketingReportsRoute
  '/marketing/scheduled': typeof MarketingScheduledRoute
  '/marketing/whatsapp': typeof MarketingWhatsappRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/my': typeof ProjectsMyRoute
  '/reports/projects': typeof ReportsProjectsRoute
  '/reports/teams': typeof ReportsTeamsRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/automation': typeof AutomationIndexRoute
  '/marketing': typeof MarketingIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workspace': typeof AuthenticatedAdminWorkspaceRoute
  '/business/expenses': typeof AuthenticatedBusinessExpensesRoute
  '/business/invoices': typeof AuthenticatedBusinessInvoicesRoute
  '/business/payments': typeof AuthenticatedBusinessPaymentsRoute
  '/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/crm/deals': typeof AuthenticatedCrmDealsRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/crm/pipeline': typeof AuthenticatedCrmPipelineRoute
  '/reports/crm': typeof AuthenticatedReportsCrmRoute
  '/settings/workspace': typeof AuthenticatedSettingsWorkspaceRoute
  '/work/documents': typeof AuthenticatedWorkDocumentsRoute
  '/work/projects': typeof AuthenticatedWorkProjectsRoute
  '/work/tasks': typeof AuthenticatedWorkTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/daily-updates': typeof DailyUpdatesRoute
  '/files': typeof FilesRoute
  '/kanban': typeof KanbanRoute
  '/leave': typeof LeaveRoute
  '/meetings': typeof MeetingsRoute
  '/milestones': typeof MilestonesRoute
  '/notifications': typeof NotificationsRoute
  '/project-templates': typeof ProjectTemplatesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/timeline': typeof TimelineRoute
  '/users': typeof UsersRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/automation/ai-usage': typeof AutomationAiUsageRoute
  '/automation/logs': typeof AutomationLogsRoute
  '/automation/templates': typeof AutomationTemplatesRoute
  '/business/quotations': typeof BusinessQuotationsRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/content-calendar': typeof MarketingContentCalendarRoute
  '/marketing/content-library': typeof MarketingContentLibraryRoute
  '/marketing/inbox': typeof MarketingInboxRoute
  '/marketing/meta': typeof MarketingMetaRoute
  '/marketing/meta-leads': typeof MarketingMetaLeadsRoute
  '/marketing/reports': typeof MarketingReportsRoute
  '/marketing/scheduled': typeof MarketingScheduledRoute
  '/marketing/whatsapp': typeof MarketingWhatsappRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/my': typeof ProjectsMyRoute
  '/reports/projects': typeof ReportsProjectsRoute
  '/reports/teams': typeof ReportsTeamsRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/automation/': typeof AutomationIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/workspace': typeof AuthenticatedAdminWorkspaceRoute
  '/_authenticated/business/expenses': typeof AuthenticatedBusinessExpensesRoute
  '/_authenticated/business/invoices': typeof AuthenticatedBusinessInvoicesRoute
  '/_authenticated/business/payments': typeof AuthenticatedBusinessPaymentsRoute
  '/_authenticated/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/_authenticated/crm/deals': typeof AuthenticatedCrmDealsRoute
  '/_authenticated/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/_authenticated/crm/pipeline': typeof AuthenticatedCrmPipelineRoute
  '/_authenticated/reports/crm': typeof AuthenticatedReportsCrmRoute
  '/_authenticated/settings/workspace': typeof AuthenticatedSettingsWorkspaceRoute
  '/_authenticated/work/documents': typeof AuthenticatedWorkDocumentsRoute
  '/_authenticated/work/projects': typeof AuthenticatedWorkProjectsRoute
  '/_authenticated/work/tasks': typeof AuthenticatedWorkTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/chat'
    | '/daily-updates'
    | '/files'
    | '/kanban'
    | '/leave'
    | '/meetings'
    | '/milestones'
    | '/notifications'
    | '/project-templates'
    | '/settings'
    | '/tasks'
    | '/timeline'
    | '/users'
    | '/ai-assistant'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/integrations'
    | '/admin/teams'
    | '/automation/ai-usage'
    | '/automation/logs'
    | '/automation/templates'
    | '/business/quotations'
    | '/crm/companies'
    | '/crm/contacts'
    | '/marketing/campaigns'
    | '/marketing/content-calendar'
    | '/marketing/content-library'
    | '/marketing/inbox'
    | '/marketing/meta'
    | '/marketing/meta-leads'
    | '/marketing/reports'
    | '/marketing/scheduled'
    | '/marketing/whatsapp'
    | '/projects/$projectId'
    | '/projects/my'
    | '/reports/projects'
    | '/reports/teams'
    | '/teams/$teamId'
    | '/automation/'
    | '/marketing/'
    | '/projects/'
    | '/teams/'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/profile'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/workspace'
    | '/business/expenses'
    | '/business/invoices'
    | '/business/payments'
    | '/crm/clients'
    | '/crm/deals'
    | '/crm/leads'
    | '/crm/pipeline'
    | '/reports/crm'
    | '/settings/workspace'
    | '/work/documents'
    | '/work/projects'
    | '/work/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/chat'
    | '/daily-updates'
    | '/files'
    | '/kanban'
    | '/leave'
    | '/meetings'
    | '/milestones'
    | '/notifications'
    | '/project-templates'
    | '/settings'
    | '/tasks'
    | '/timeline'
    | '/users'
    | '/ai-assistant'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/integrations'
    | '/admin/teams'
    | '/automation/ai-usage'
    | '/automation/logs'
    | '/automation/templates'
    | '/business/quotations'
    | '/crm/companies'
    | '/crm/contacts'
    | '/marketing/campaigns'
    | '/marketing/content-calendar'
    | '/marketing/content-library'
    | '/marketing/inbox'
    | '/marketing/meta'
    | '/marketing/meta-leads'
    | '/marketing/reports'
    | '/marketing/scheduled'
    | '/marketing/whatsapp'
    | '/projects/$projectId'
    | '/projects/my'
    | '/reports/projects'
    | '/reports/teams'
    | '/teams/$teamId'
    | '/automation'
    | '/marketing'
    | '/projects'
    | '/teams'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/profile'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/workspace'
    | '/business/expenses'
    | '/business/invoices'
    | '/business/payments'
    | '/crm/clients'
    | '/crm/deals'
    | '/crm/leads'
    | '/crm/pipeline'
    | '/reports/crm'
    | '/settings/workspace'
    | '/work/documents'
    | '/work/projects'
    | '/work/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/chat'
    | '/daily-updates'
    | '/files'
    | '/kanban'
    | '/leave'
    | '/meetings'
    | '/milestones'
    | '/notifications'
    | '/project-templates'
    | '/settings'
    | '/tasks'
    | '/timeline'
    | '/users'
    | '/_authenticated/ai-assistant'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/integrations'
    | '/admin/teams'
    | '/automation/ai-usage'
    | '/automation/logs'
    | '/automation/templates'
    | '/business/quotations'
    | '/crm/companies'
    | '/crm/contacts'
    | '/marketing/campaigns'
    | '/marketing/content-calendar'
    | '/marketing/content-library'
    | '/marketing/inbox'
    | '/marketing/meta'
    | '/marketing/meta-leads'
    | '/marketing/reports'
    | '/marketing/scheduled'
    | '/marketing/whatsapp'
    | '/projects/$projectId'
    | '/projects/my'
    | '/reports/projects'
    | '/reports/teams'
    | '/teams/$teamId'
    | '/automation/'
    | '/marketing/'
    | '/projects/'
    | '/teams/'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/profile'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/workspace'
    | '/_authenticated/business/expenses'
    | '/_authenticated/business/invoices'
    | '/_authenticated/business/payments'
    | '/_authenticated/crm/clients'
    | '/_authenticated/crm/deals'
    | '/_authenticated/crm/leads'
    | '/_authenticated/crm/pipeline'
    | '/_authenticated/reports/crm'
    | '/_authenticated/settings/workspace'
    | '/_authenticated/work/documents'
    | '/_authenticated/work/projects'
    | '/_authenticated/work/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ChatRoute: typeof ChatRoute
  DailyUpdatesRoute: typeof DailyUpdatesRoute
  FilesRoute: typeof FilesRoute
  KanbanRoute: typeof KanbanRoute
  LeaveRoute: typeof LeaveRoute
  MeetingsRoute: typeof MeetingsRoute
  MilestonesRoute: typeof MilestonesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectTemplatesRoute: typeof ProjectTemplatesRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TimelineRoute: typeof TimelineRoute
  UsersRoute: typeof UsersRoute
  AdminApiRoute: typeof AdminApiRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AutomationAiUsageRoute: typeof AutomationAiUsageRoute
  AutomationLogsRoute: typeof AutomationLogsRoute
  AutomationTemplatesRoute: typeof AutomationTemplatesRoute
  BusinessQuotationsRoute: typeof BusinessQuotationsRoute
  CrmCompaniesRoute: typeof CrmCompaniesRoute
  CrmContactsRoute: typeof CrmContactsRoute
  MarketingCampaignsRoute: typeof MarketingCampaignsRoute
  MarketingContentCalendarRoute: typeof MarketingContentCalendarRoute
  MarketingContentLibraryRoute: typeof MarketingContentLibraryRoute
  MarketingInboxRoute: typeof MarketingInboxRoute
  MarketingMetaRoute: typeof MarketingMetaRoute
  MarketingMetaLeadsRoute: typeof MarketingMetaLeadsRoute
  MarketingReportsRoute: typeof MarketingReportsRoute
  MarketingScheduledRoute: typeof MarketingScheduledRoute
  MarketingWhatsappRoute: typeof MarketingWhatsappRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsMyRoute: typeof ProjectsMyRoute
  ReportsProjectsRoute: typeof ReportsProjectsRoute
  ReportsTeamsRoute: typeof ReportsTeamsRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  AutomationIndexRoute: typeof AutomationIndexRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-updates': {
      id: '/daily-updates'
      path: '/daily-updates'
      fullPath: '/daily-updates'
      preLoaderRoute: typeof DailyUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-templates': {
      id: '/project-templates'
      path: '/project-templates'
      fullPath: '/project-templates'
      preLoaderRoute: typeof ProjectTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/admin/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/': {
      id: '/automation/'
      path: '/automation'
      fullPath: '/automation/'
      preLoaderRoute: typeof AutomationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/ai-usage': {
      id: '/automation/ai-usage'
      path: '/automation/ai-usage'
      fullPath: '/automation/ai-usage'
      preLoaderRoute: typeof AutomationAiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/logs': {
      id: '/automation/logs'
      path: '/automation/logs'
      fullPath: '/automation/logs'
      preLoaderRoute: typeof AutomationLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/templates': {
      id: '/automation/templates'
      path: '/automation/templates'
      fullPath: '/automation/templates'
      preLoaderRoute: typeof AutomationTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/quotations': {
      id: '/business/quotations'
      path: '/business/quotations'
      fullPath: '/business/quotations'
      preLoaderRoute: typeof BusinessQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/companies': {
      id: '/crm/companies'
      path: '/crm/companies'
      fullPath: '/crm/companies'
      preLoaderRoute: typeof CrmCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/campaigns': {
      id: '/marketing/campaigns'
      path: '/marketing/campaigns'
      fullPath: '/marketing/campaigns'
      preLoaderRoute: typeof MarketingCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/content-calendar': {
      id: '/marketing/content-calendar'
      path: '/marketing/content-calendar'
      fullPath: '/marketing/content-calendar'
      preLoaderRoute: typeof MarketingContentCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/content-library': {
      id: '/marketing/content-library'
      path: '/marketing/content-library'
      fullPath: '/marketing/content-library'
      preLoaderRoute: typeof MarketingContentLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/inbox': {
      id: '/marketing/inbox'
      path: '/marketing/inbox'
      fullPath: '/marketing/inbox'
      preLoaderRoute: typeof MarketingInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/meta': {
      id: '/marketing/meta'
      path: '/marketing/meta'
      fullPath: '/marketing/meta'
      preLoaderRoute: typeof MarketingMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/meta-leads': {
      id: '/marketing/meta-leads'
      path: '/marketing/meta-leads'
      fullPath: '/marketing/meta-leads'
      preLoaderRoute: typeof MarketingMetaLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/reports': {
      id: '/marketing/reports'
      path: '/marketing/reports'
      fullPath: '/marketing/reports'
      preLoaderRoute: typeof MarketingReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/scheduled': {
      id: '/marketing/scheduled'
      path: '/marketing/scheduled'
      fullPath: '/marketing/scheduled'
      preLoaderRoute: typeof MarketingScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/whatsapp': {
      id: '/marketing/whatsapp'
      path: '/marketing/whatsapp'
      fullPath: '/marketing/whatsapp'
      preLoaderRoute: typeof MarketingWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/my': {
      id: '/projects/my'
      path: '/projects/my'
      fullPath: '/projects/my'
      preLoaderRoute: typeof ProjectsMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/projects': {
      id: '/reports/projects'
      path: '/reports/projects'
      fullPath: '/reports/projects'
      preLoaderRoute: typeof ReportsProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/teams': {
      id: '/reports/teams'
      path: '/reports/teams'
      fullPath: '/reports/teams'
      preLoaderRoute: typeof ReportsTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/profile': {
      id: '/_authenticated/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AuthenticatedAdminProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/workspace': {
      id: '/_authenticated/admin/workspace'
      path: '/admin/workspace'
      fullPath: '/admin/workspace'
      preLoaderRoute: typeof AuthenticatedAdminWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/expenses': {
      id: '/_authenticated/business/expenses'
      path: '/business/expenses'
      fullPath: '/business/expenses'
      preLoaderRoute: typeof AuthenticatedBusinessExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/invoices': {
      id: '/_authenticated/business/invoices'
      path: '/business/invoices'
      fullPath: '/business/invoices'
      preLoaderRoute: typeof AuthenticatedBusinessInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/payments': {
      id: '/_authenticated/business/payments'
      path: '/business/payments'
      fullPath: '/business/payments'
      preLoaderRoute: typeof AuthenticatedBusinessPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/clients': {
      id: '/_authenticated/crm/clients'
      path: '/crm/clients'
      fullPath: '/crm/clients'
      preLoaderRoute: typeof AuthenticatedCrmClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/deals': {
      id: '/_authenticated/crm/deals'
      path: '/crm/deals'
      fullPath: '/crm/deals'
      preLoaderRoute: typeof AuthenticatedCrmDealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/leads': {
      id: '/_authenticated/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AuthenticatedCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/pipeline': {
      id: '/_authenticated/crm/pipeline'
      path: '/crm/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof AuthenticatedCrmPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/crm': {
      id: '/_authenticated/reports/crm'
      path: '/reports/crm'
      fullPath: '/reports/crm'
      preLoaderRoute: typeof AuthenticatedReportsCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/workspace': {
      id: '/_authenticated/settings/workspace'
      path: '/settings/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof AuthenticatedSettingsWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/documents': {
      id: '/_authenticated/work/documents'
      path: '/work/documents'
      fullPath: '/work/documents'
      preLoaderRoute: typeof AuthenticatedWorkDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/projects': {
      id: '/_authenticated/work/projects'
      path: '/work/projects'
      fullPath: '/work/projects'
      preLoaderRoute: typeof AuthenticatedWorkProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/tasks': {
      id: '/_authenticated/work/tasks'
      path: '/work/tasks'
      fullPath: '/work/tasks'
      preLoaderRoute: typeof AuthenticatedWorkTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminProfileRoute: typeof AuthenticatedAdminProfileRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWorkspaceRoute: typeof AuthenticatedAdminWorkspaceRoute
  AuthenticatedBusinessExpensesRoute: typeof AuthenticatedBusinessExpensesRoute
  AuthenticatedBusinessInvoicesRoute: typeof AuthenticatedBusinessInvoicesRoute
  AuthenticatedBusinessPaymentsRoute: typeof AuthenticatedBusinessPaymentsRoute
  AuthenticatedCrmClientsRoute: typeof AuthenticatedCrmClientsRoute
  AuthenticatedCrmDealsRoute: typeof AuthenticatedCrmDealsRoute
  AuthenticatedCrmLeadsRoute: typeof AuthenticatedCrmLeadsRoute
  AuthenticatedCrmPipelineRoute: typeof AuthenticatedCrmPipelineRoute
  AuthenticatedReportsCrmRoute: typeof AuthenticatedReportsCrmRoute
  AuthenticatedSettingsWorkspaceRoute: typeof AuthenticatedSettingsWorkspaceRoute
  AuthenticatedWorkDocumentsRoute: typeof AuthenticatedWorkDocumentsRoute
  AuthenticatedWorkProjectsRoute: typeof AuthenticatedWorkProjectsRoute
  AuthenticatedWorkTasksRoute: typeof AuthenticatedWorkTasksRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminProfileRoute: AuthenticatedAdminProfileRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWorkspaceRoute: AuthenticatedAdminWorkspaceRoute,
  AuthenticatedBusinessExpensesRoute: AuthenticatedBusinessExpensesRoute,
  AuthenticatedBusinessInvoicesRoute: AuthenticatedBusinessInvoicesRoute,
  AuthenticatedBusinessPaymentsRoute: AuthenticatedBusinessPaymentsRoute,
  AuthenticatedCrmClientsRoute: AuthenticatedCrmClientsRoute,
  AuthenticatedCrmDealsRoute: AuthenticatedCrmDealsRoute,
  AuthenticatedCrmLeadsRoute: AuthenticatedCrmLeadsRoute,
  AuthenticatedCrmPipelineRoute: AuthenticatedCrmPipelineRoute,
  AuthenticatedReportsCrmRoute: AuthenticatedReportsCrmRoute,
  AuthenticatedSettingsWorkspaceRoute: AuthenticatedSettingsWorkspaceRoute,
  AuthenticatedWorkDocumentsRoute: AuthenticatedWorkDocumentsRoute,
  AuthenticatedWorkProjectsRoute: AuthenticatedWorkProjectsRoute,
  AuthenticatedWorkTasksRoute: AuthenticatedWorkTasksRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ChatRoute: ChatRoute,
  DailyUpdatesRoute: DailyUpdatesRoute,
  FilesRoute: FilesRoute,
  KanbanRoute: KanbanRoute,
  LeaveRoute: LeaveRoute,
  MeetingsRoute: MeetingsRoute,
  MilestonesRoute: MilestonesRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectTemplatesRoute: ProjectTemplatesRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TimelineRoute: TimelineRoute,
  UsersRoute: UsersRoute,
  AdminApiRoute: AdminApiRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AutomationAiUsageRoute: AutomationAiUsageRoute,
  AutomationLogsRoute: AutomationLogsRoute,
  AutomationTemplatesRoute: AutomationTemplatesRoute,
  BusinessQuotationsRoute: BusinessQuotationsRoute,
  CrmCompaniesRoute: CrmCompaniesRoute,
  CrmContactsRoute: CrmContactsRoute,
  MarketingCampaignsRoute: MarketingCampaignsRoute,
  MarketingContentCalendarRoute: MarketingContentCalendarRoute,
  MarketingContentLibraryRoute: MarketingContentLibraryRoute,
  MarketingInboxRoute: MarketingInboxRoute,
  MarketingMetaRoute: MarketingMetaRoute,
  MarketingMetaLeadsRoute: MarketingMetaLeadsRoute,
  MarketingReportsRoute: MarketingReportsRoute,
  MarketingScheduledRoute: MarketingScheduledRoute,
  MarketingWhatsappRoute: MarketingWhatsappRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsMyRoute: ProjectsMyRoute,
  ReportsProjectsRoute: ReportsProjectsRoute,
  ReportsTeamsRoute: ReportsTeamsRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  AutomationIndexRoute: AutomationIndexRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
